---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: 输出 ansible_env.HOME 环境变量
      debug:
        msg: "HOME 环境变量为：{{ ansible_env.HOME }}"

    - name: 安装 oh-my-zsh
      shell: |
        RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: 创建 ~/.ssh 软链接
      file:
        src: "{{ ansible_env.HOME }}/dev_env/.ssh"
        dest: "{{ ansible_env.HOME }}/.ssh"
        state: link
        force: yes

    - name: 创建 ~/.zshrc 软链接
      file:
        src: "{{ ansible_env.HOME }}/dev_env/.zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        state: link
        force: yes

    - name: 安装 tree (macOS 使用 Homebrew)
      homebrew:
        name: tree
        state: present
      when: ansible_system == "Darwin"

    - name: 安装 tree (Linux 使用 package 模块)
      apt:
        name: tree
        state: present
      when: ansible_system != "Darwin"
